@startuml 239_person
actor ユーザ
boundary ブラウザ
control web.php
control PersonController
entity Person
boundary person.index.blade

ユーザ -> ブラウザ:該当ページをリクエスト[person]
ブラウザ -> web.php: GET[person]
web.php -> PersonController:@index
PersonController -> Person:all()
PersonController <-- Person
PersonController -> person.index.blade
@enduml
