@startuml 255_person_add
actor ユーザ
boundary ブラウザ
control web.php
control PersonController
entity Person
boundary person.add.blade
boundary person.index.blade

ユーザ -> ブラウザ:該当ページをリクエスト[person/add]
ブラウザ -> web.php: GET[person/add]
web.php -> PersonController:@add
PersonController -> person.add.blade
ユーザ -> person.add.blade:sendボタン押下
person.add.blade -> web.php:POST
web.php -> PersonController:@create
PersonController -> Person:fill()
PersonController <-- Person:
PersonController -> web.php:リダイレクト[/person]
web.php -> PersonController:@index
PersonController -> Person:all()
PersonController <-- Person
PersonController -> person.index.blade
@enduml
