@startuml 300_RESTful_create
actor ユーザ
boundary ブラウザ
control web.php
control RestappController
boundary create.blade.php
entity Restdata

ユーザ -> ブラウザ:該当ページをリクエスト[/rest/create]
ブラウザ -> web.php: GET[/rest/create]
web.php -> RestappController:@create
RestappController -> create.blade.php
ユーザ -> create.blade.php:sendボタンを押下
create.blade.php -> web.php:POST[/rest]
web.php -> RestappController:@store
RestappController -> Restdata:save()
RestappController <-- Restdata
RestappController -> web.php:GET[/rest]
web.php -> RestappController:@index
RestappController -> Restdata:all()
RestappController <-- Restdata

@enduml
