@startuml 46_hello_other
actor ユーザ
boundary ブラウザ
control web.php
control HelloController

ユーザ -> ブラウザ:該当ページをリクエスト[/hello]
ブラウザ -> web.php: GET[/hello]
web.php -> HelloController:@index
HelloController -> ブラウザ:

ユーザ -> ブラウザ:該当ページをリクエスト[/hello/other]
ブラウザ -> web.php: GET[/hello/other]
web.php -> HelloController:@other
HelloController -> ブラウザ:
@enduml
