@startuml jissyu5_3
actor ユーザ
boundary ブラウザ
control web.php
control Jissyu5_3Controller
boundary index.blade.php
boundary show.blade.php
boundary add.blade.php
boundary edit.blade.php
boundary del.blade.php

ユーザ -> ブラウザ:該当ページをリクエスト[/jissyu12]
ブラウザ -> web.php: GET[/jissyu12]
web.php -> Jissyu5_3Controller:@index
Jissyu5_3Controller -> index.blade.php

ユーザ -> index.blade.php:詳細リンクを押下
index.blade.php -> web.php:GET[/jissyu12/show]
web.php -> Jissyu5_3Controller:@show
Jissyu5_3Controller -> show.blade.php

ユーザ -> index.blade.php:新規登録リンクを押下
index.blade.php -> web.php:GET[/jissyu12/add]
web.php -> Jissyu5_3Controller:@add
Jissyu5_3Controller -> add.blade.php
ユーザ -> add.blade.php:新規登録ボタンを押下
add.blade.php -> web.php:POST[/jissyu12/create]
web.php -> Jissyu5_3Controller:@create
Jissyu5_3Controller -> index.blade.php

ユーザ -> index.blade.php:更新リンクを押下
index.blade.php -> web.php:GET[/jissyu12/edit]
web.php -> Jissyu5_3Controller:@edit
Jissyu5_3Controller -> edit.blade.php
ユーザ -> edit.blade.php:更新ボタンを押下
edit.blade.php -> web.php:POST[/jissyu12/update]
web.php -> Jissyu5_3Controller:@update
Jissyu5_3Controller -> index.blade.php

ユーザ -> index.blade.php:削除リンクを押下
index.blade.php -> web.php:GET[/jissyu12/del]
web.php -> Jissyu5_3Controller:@del
Jissyu5_3Controller -> del.blade.php
ユーザ -> del.blade.php:削除ボタンを押下
del.blade.php -> web.php:POST[/jissyu12/remove]
web.php -> Jissyu5_3Controller:@remove
Jissyu5_3Controller -> index.blade.php
@enduml
