@startuml kouka1_1
actor ユーザ
boundary ブラウザ
control web.php
control Kouka1_1Controller
boundary kouka1_1.index.blade.php
boundary layouts.kouka1_1.blade.php
boundary components.menu.blade.php
boundary components.subview.blade.php


ユーザ -> ブラウザ:該当ページをリクエスト[/kouka1_1]
ブラウザ -> web.php: GET[/kouka1_1]
web.php -> Kouka1_1Controller:@index
Kouka1_1Controller -> kouka1_1.index.blade.php
kouka1_1.index.blade.php -> layouts.kouka1_1.blade.php:@extends
kouka1_1.index.blade.php <-- layouts.kouka1_1.blade.php
kouka1_1.index.blade.php -> components.menu.blade.php:@component
kouka1_1.index.blade.php <-- components.menu.blade.php
kouka1_1.index.blade.php -> components.subview.blade.php:@include
kouka1_1.index.blade.php <-- components.subview.blade.php

@enduml
