@startuml kouka2_2
actor ユーザ
boundary ブラウザ
control web.php
control Kouka2_2Controller
entity Restdata
boundary index.blade.php
boundary show.blade.php
boundary add.blade.php
boundary edit.blade.php
boundary del.blade.php

ユーザ -> ブラウザ:該当ページをリクエスト[/kouka2_2]
ブラウザ -> web.php: GET[/kouka2_2]
web.php -> Kouka2_2Controller:@index
Kouka2_2Controller -> Restdata:all()
Kouka2_2Controller <- Restdata
Kouka2_2Controller -> index.blade.php

ユーザ -> index.blade.php:検索ボタンを押下
index.blade.php -> web.php:GET[/kouka2_2/find]
web.php -> Kouka2_2Controller:@find
Kouka2_2Controller -> Restdata:where()->first()
Kouka2_2Controller <- Restdata
Kouka2_2Controller -> show.blade.php

ユーザ -> index.blade.php:詳細リンクを押下
index.blade.php -> web.php:GET[/kouka2_2/show]
web.php -> Kouka2_2Controller:@show
Kouka2_2Controller -> Restdata:where()->first()
Kouka2_2Controller <- Restdata
Kouka2_2Controller -> show.blade.php

ユーザ -> index.blade.php:新規登録リンクを押下
index.blade.php -> web.php:GET[/kouka2_2/add]
web.php -> Kouka2_2Controller:@add
Kouka2_2Controller -> add.blade.php

ユーザ -> add.blade.php:新規登録ボタンを押下
add.blade.php -> web.php:POST[/kouka2_2/create]
web.php -> Kouka2_2Controller:@create
Kouka2_2Controller -> Restdata:all()
Kouka2_2Controller <- Restdata
Kouka2_2Controller -> index.blade.php

ユーザ -> index.blade.php:更新リンクを押下
index.blade.php -> web.php:GET[/kouka2_2/edit]
web.php -> Kouka2_2Controller:@edit
Kouka2_2Controller -> Restdata:find()
Kouka2_2Controller <- Restdata
Kouka2_2Controller -> edit.blade.php

ユーザ -> edit.blade.php:更新ボタンを押下
edit.blade.php -> web.php:POST[/kouka2_2/update]
web.php -> Kouka2_2Controller:@update
Kouka2_2Controller -> Restdata:find()
Kouka2_2Controller <- Restdata
Kouka2_2Controller -> index.blade.php

ユーザ -> index.blade.php:削除リンクを押下
index.blade.php -> web.php:GET[/kouka2_2/del]
web.php -> Kouka2_2Controller:@del
Kouka2_2Controller -> Restdata:find()
Kouka2_2Controller <- Restdata
Kouka2_2Controller -> del.blade.php

ユーザ -> del.blade.php:削除ボタンを押下
del.blade.php -> web.php:POST[/kouka2_2/remove]
web.php -> Kouka2_2Controller:@remove
Kouka2_2Controller -> Restdata:find()->delete()
Kouka2_2Controller <- Restdata
Kouka2_2Controller -> index.blade.php
@enduml
