@startuml Kouka2_1
actor ユーザ
boundary ブラウザ
control web.php
control Kouka2_1Controller
entity Restdata
boundary index.blade.php
boundary show.blade.php

ユーザ -> ブラウザ:該当ページをリクエスト[/kouka2_1]
ブラウザ -> web.php: GET[/kouka2_1]
web.php -> Kouka2_1Controller:@index
Kouka2_1Controller -> Restdata:all()
Kouka2_1Controller <-- Restdata
Kouka2_1Controller -> index.blade.php

ユーザ -> ブラウザ:検索ボタンを押下
ブラウザ -> web.php: GET[/kouka2_1/find]
web.php -> Kouka2_1Controller:@find
Kouka2_1Controller -> Restdata:where()->first()
Kouka2_1Controller <-- Restdata
Kouka2_1Controller -> show.blade.php

@enduml
